### ISSUE TITLE
UI render in windows 10

### ISSUE THREAD

**Issue by kinsleykajiva** [patrickmoffitt/local-sqlite-example#1]
i have downloaded your project and i ran it, well it seems like there is just a white screen with no UI as you have put in your screenshots. I am using windows 10-X64 .
Here is what i am getting when i rub the project .
![errr_view](https://user-images.githubusercontent.com/8996252/34912341-5576b07e-f8f0-11e7-8e61-142e32499472.PNG)
However i am grateful for the project, it one example that i have been looking that solves the sqlite problem in the electron.

**Comment by patrickmoffitt** [comment]
Upon inspection the console shows that [popper.js](https://www.npmjs.com/package/popper.js) is not being found. 
```
module.js:472 Uncaught Error: Cannot find module 'popper.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\User\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\User\Electron Projects\local-sqlite-example\node_modules\bootstrap\dist\js\bootstrap.js:7:101
    at Object.<anonymous> (C:\Users\User\Electron Projects\local-sqlite-example\node_modules\bootstrap\dist\js\bootstrap.js:10:2)
    at Object.<anonymous> (C:\Users\User\Electron Projects\local-sqlite-example\node_modules\bootstrap\dist\js\bootstrap.js:3894:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```
This is a dependency from bootstrap@4.0.0-beta.3. Since the [package.json](https://github.com/patrickmoffitt/local-sqlite-example/blob/master/package.json) includes this requirement:
```
  "dependencies": {
    "bootstrap": "4.0.0-beta.3",
    "cheerio": "^0.22.0",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.9",
    "sql.js": "^0.4.0",
    "tether": "^1.4.0"
}
```
I'm not sure what I can do about it as a developer. Meanwhile, as a work around, use your favorite package manager to install popper.js. I tried this on my own Win10 and it worked for me. Details of how to install can be found at the popper.js link above.

I use [yarn](https://yarnpkg.com/en/) as my package manager. After cloning the project into Win10 it shows that popper.js is missing.
```
C:\Users\User\Electron Projects\local-sqlite-example>yarn check
yarn check v1.3.2
error "popper.js" not installed
error "readable-stream#safe-buffer" not installed
error Found 2 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```
I used yarn to install the missing package and that solved the issue.
```
C:\Users\User\Electron Projects\local-sqlite-example>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.03s.

C:\Users\User\Electron Projects\local-sqlite-example>
```
